# Generated by Django 5.1.6 on 2025-03-12 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_purchasehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='purchase_date',
            new_name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='total_price',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='apellido',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='celular',
            field=models.CharField(default='No registrado', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='metodo_pago',
            field=models.CharField(default='No especificado', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='municipio',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='nombre',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='productos',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='residencia',
            field=models.TextField(default='No especificado'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
